import { Component } from '@angular/core';
import { Announcement } from 'src/app/core/models/announcement.model';

@Component({
  selector: 'app-requested',
  templateUrl: './requested.component.html',
  styleUrls: ['./requested.component.scss']
})
export class RequestedComponent {
  announcements: Announcement[] = [
    {
      title: 'Гитара Fender',
      desc: "Продаю гитару Fender",
      image: '../assets/img/cards/guitar.png',
      price: '20 000',
      location: 'Москва, Ленина, 33',
      date: '28.03.2023',
      link: 'url',
    },
    {
      title: 'Гитара Fender',
      desc: "Продаю гитару Fender",
      image: '../assets/img/cards/guitar.png',
      price: '20 000',
      location: 'Москва, Ленина, 33',
      date: '28.03.2023',
      link: 'url',
    },
    {
      title: 'Гитара Fender',
      desc: "Продаю гитару Fender",
      image: '../assets/img/cards/guitar.png',
      price: '20 000',
      location: 'Москва, Ленина, 33',
      date: '28.03.2023',
      link: 'url',
    },
    {
      title: 'Гитара Fender',
      desc: "Продаю гитару Fender",
      image: '../assets/img/cards/guitar.png',
      price: '20 000',
      location: 'Москва, Ленина, 33',
      date: '28.03.2023',
      link: 'url',
    },
    {
      title: 'Гитара Fender',
      desc: "Продаю гитару Fender",
      image: '../assets/img/cards/guitar.png',
      price: '20 000',
      location: 'Москва, Ленина, 33',
      date: '28.03.2023',
      link: 'url',
    },
    {
      title: 'Гитара Fender',
      desc: "Продаю гитару Fender",
      image: '../assets/img/cards/guitar.png',
      price: '20 000',
      location: 'Москва, Ленина, 33',
      date: '28.03.2023',
      link: 'url',
    },
    {
      title: 'Гитара Fender',
      desc: "Продаю гитару Fender",
      image: '../assets/img/cards/guitar.png',
      price: '20 000',
      location: 'Москва, Ленина, 33',
      date: '28.03.2023',
      link: 'url',
    },
    {
      title: 'Гитара Fender',
      desc: "Продаю гитару Fender",
      image: '../assets/img/cards/guitar.png',
      price: '20 000',
      location: 'Москва, Ленина, 33',
      date: '28.03.2023',
      link: 'url',
    },
    {
      title: 'Гитара Fender',
      desc: "Продаю гитару Fender",
      image: '../assets/img/cards/guitar.png',
      price: '20 000',
      location: 'Москва, Ленина, 33',
      date: '28.03.2023',
      link: 'url',
    },
    {
      title: 'Гитара Fender',
      desc: "Продаю гитару Fender",
      image: '../assets/img/cards/guitar.png',
      price: '20 000',
      location: 'Москва, Ленина, 33',
      date: '28.03.2023',
      link: 'url',
    },
    {
      title: 'Гитара Fender',
      desc: "Продаю гитару Fender",
      image: '../assets/img/cards/guitar.png',
      price: '20 000',
      location: 'Москва, Ленина, 33',
      date: '28.03.2023',
      link: 'url',
    },
  ] 
}
